// shopData.ts

export const products = [
    {
        productId: 999,
        productName: "Pagal Toil Hoodie",
        size: "L",
        colour: "Black",
        price: 2999.99,
        quantityInStock: 3,
        image: "src/assets/products/hoodie-1.png",
    },
    {
        productId: 999,
        productName: "Pagal Toli Logo Patch",
        size: "6in x 4in (L x B)",
        colour: "Black-White",
        price: 299.99,
        quantityInStock: 22,
        image: "src/assets/products/tag-1.png",
    },
    {
        productId: 1001,
        productName: "Motorcycle Helmet",
        size: "L",
        colour: "Black",
        price: 129.99,
        quantityInStock: 25,
        image: "src/assets/products/helmet-1.png",
    },
    {
        productId: 1002,
        productName: "Leather Riding Jacket",
        size: "M",
        colour: "Brown",
        price: 299.99,
        quantityInStock: 15,
        image: "src/assets/products/jacket-1.png",
    },
    {
        productId: 1003,
        productName: "Riding Gloves",
        size: "One Size",
        colour: "Black",
        price: 39.99,
        quantityInStock: 50,
        image: "src/assets/products/gloves-1.png",
    },
    {
        productId: 1004,
        productName: "Motorbike Boots",
        size: "42",
        colour: "Black",
        price: 199.99,
        quantityInStock: 10,
        image: "src/assets/products/boots-1.png",
    },
    {
        productId: 1005,
        productName: "Motorcycle Goggles",
        size: "One Size",
        colour: "Clear",
        price: 29.99,
        quantityInStock: 100,
        image: "src/assets/products/goggles-1.png",
    },

];
